//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ward")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub district_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::district::Entity",
        from = "Column::DistrictId",
        to = "super::district::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    District,
    #[sea_orm(has_many = "super::listing::Entity")]
    Listing,
}

impl Related<super::district::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::District.def()
    }
}

impl Related<super::listing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Listing.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
